spring.application.name=analytics-consumer

server.port=8084

spring.activemq.broker-url=tcp://127.0.0.1:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.jms.pub-sub-domain=true

app.jms.topic=order.created.topic